name: Deploy AirSight

on:
  push: { branches: [main] }
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Vendor dependencies into .python_packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -t .python_packages/lib/site-packages
          ls -la .python_packages/lib/site-packages | head || true

      - name: Create deploy zip
        run: |
          zip -r site.zip . \
            -x "venv/*" ".git/*" ".github/*" "__pycache__/*"

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: AirSight
          slot-name: Production
          package: site.zip
