# .github/workflows/main_airsight.yml
name: Build and deploy Python app to Azure Web App - AirSight

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ✅ Install all dependencies into a local folder that we deploy
      - name: Vendor Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt \
            -t .python_packages/lib/site-packages

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ED1E678B6E614660AF30273B1A007894 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73B15276B03E43B2BB4F3E4237D4B2B1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B9DE7F65245D49E7AD661C85BD17DF18 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AirSight'
          # slot-name: 'production'            # (optional) lowercase if you use it
          package: '.'                         # deploy the prebuilt package
