name: Build and deploy AirSight

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Vendor dependencies into .python_packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -t .python_packages/lib/site-packages
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          if-no-files-found: error
          path: |
            .
            !.git/
            !.github/
            !venv/
            !**/__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: { contents: read, id-token: write }
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .     # flatten into root
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: AirSight
          slot-name: Production
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
