name: Build & Deploy AirSight to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-airsight
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: AirSight            # <-- EDIT if your App Service name differs
      SLOT_NAME: Production         # remove this line if using the default slot
      DEPLOY_PATH: .                # will be overwritten if a build folder is found

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Optional: Node build if package.json exists ----------
      - name: Detect Node project
        id: detect_node
        shell: bash
        run: |
          if [ -f "package.json" ]; then
            echo "has_node=true" >> $GITHUB_OUTPUT
          else
            echo "has_node=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        if: steps.detect_node.outputs.has_node == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & Build (Node)
        if: steps.detect_node.outputs.has_node == 'true'
        run: |
          npm ci
          npm run build --if-present

      # ---------- Decide what to deploy ----------
      - name: Choose deploy path
        id: choose_path
        shell: bash
        run: |
          for d in build dist out .next nextjs .output public; do
            if [ -d "$d" ]; then
              echo "Found build folder: $d"
              echo "DEPLOY_PATH=$d" >> $GITHUB_ENV
              break
            fi
          done
          echo "Deploying from: ${DEPLOY_PATH}"
          ls -la "${DEPLOY_PATH}"

      # ---------- Preflight: verify secrets are visible to this job ----------
      - name: Verify Azure secrets
        shell: bash
        env:
          CID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32FBB5890BF24D90BABB0420ADE93AAC }}
          TID: ${{ secrets.AZUREAPPSERVICE_TENANTID_E90AD2769AFE4313B72013DAC9E3F102 }}
          SID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6EC81AD7847842CAA14260C11B733745 }}
        run: |
          MISSING=0
          [ -z "$CID" ] && echo "::error::Missing secret: client-id" && MISSING=1
          [ -z "$TID" ] && echo "::error::Missing secret: tenant-id" && MISSING=1
          [ -z "$SID" ] && echo "::error::Missing secret: subscription-id" && MISSING=1
          [ $MISSING -eq 1 ] && exit 1

      # ---------- Azure Login (uses your selected repo secrets) ----------
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32FBB5890BF24D90BABB0420ADE93AAC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E90AD2769AFE4313B72013DAC9E3F102 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6EC81AD7847842CAA14260C11B733745 }}

      # ---------- Deploy ----------
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          package: ${{ env.DEPLOY_PATH }}
